.TH "DOCKER-INJECTOR" "8" "March 2020" "" ""
.SH "NAME"
\fBdocker-injector\fR - Injecting Docker Reverse Proxy
.SH "SYNOPSIS"
.P
\fBdocker-injector\fR \[lB]\fB-h\fR|\fB--help\fR\[rB] \[lB]\fB-V\fR|\fB--version\fR\[rB] \[lB]\fB-d\fR|\fB--daemon\fR\[rB] \[lB]\fB-p\fR|\fB--pid-file\fR \fIpid-file\fR\[rB] \[lB]\fB-l\fR|\fB--log-file\fR \fIlog-file\fR\[rB] \[lB]\fB-v\fR|\fB--log-level\fR \fIlog-level\fR\[rB] \[lB]\fB-L\fR|\fB--label\fR \fIkey\fR\fB=\fR\fIvalue\fR\[rB] \[lB]\fB-E\fR|\fB--environment\fR \fIkey\fR\fB=\fR\fIvalue\fR\[rB] \[lB]\fB-B\fR|\fB--bind\fR \fIlocal-dir\fR\fB:\fR\fIremote-dir\fR\[lB]\fB:\fR\fIoptions\fR\[rB]\[rB] \[lB]\fB-a\fR|\fB--accept \fR \fIlocal-address\fR:\fIlocal-port\fR|\fIunix-socket-path\fR\[rB] \[lB]\fB-c\fR|\fB--connect\fR \fIremote-address\fR:\fIremote-port\fR|\fIunix-socket-path\fR\[rB]
.SH "DESCRIPTION"
.P
\fBdocker-injector\fR(8) is a small reverse proxy for the \fBdockerd\fR(8) daemon socket (\fB/var/lib/docker.sock\fR or \fB127.0.0.1:2375\fR) which allows you to transparently inject label, environment and bind mount information for the creation of Docker containers into the HTTP/REST requests received on the server-side by Docker clients like \fBdocker\fR(1) or \fBdrone-runner-docker\fR(8). This effectively allows you to emulate the \fBdocker\fR(1) options \fB-l\fR (label), \fB-e\fR (environment) and \fB-v\fR (bind mount) in case you cannot directly control the container creation on the client-side.
.SH "OPTIONS"
.P
The following command-line options and arguments exist:
.RS 0
.IP \(bu 4
\[lB]\fB-h\fR|\fB--help\fR\[rB]: Show program usage information only.
.IP \(bu 4
\[lB]\fB-V\fR|\fB--version\fR\[rB]: Show program version information only.
.IP \(bu 4
\[lB]\fB-d\fR|\fB--daemon\fR\[rB]: Detach from terminal into a daemon process. This usually should be combined with option \fB-l\fR|--log-file`.
.IP \(bu 4
\[lB]\fB-p\fR|\fB--pid-file\fR \fIpid-file\fR\[rB]: Write process id (PID) to \fIpid-file\fR.
.IP \(bu 4
\[lB]\fB-l\fR|\fB--log-file\fR \fIlog-file\fR\[rB]: Write process log messages to \fIlog-file\fR. If \fIlog-file\fR is \fB-\fR (the default), it logs to \fBstdout\fR.
.IP \(bu 4
\[lB]\fB-v\fR|\fB--log-level\fR \fIlog-level\fR\[rB]: Set the verbosity/log-level of the log messages. The \fIlog-level\fR can be \fB0\fR (only error messages), \fB1\fR (error and warning messages, and the default), \fB2\fR (error, warning and informational messages) or \fB3\fR (error, warning, informational and debug messages).
.IP \(bu 4
\[lB]\fB-L\fR|\fB--label\fR \fIkey\fR\fB=\fR\fIvalue\fR\[rB]: Inject a Docker label into the created containers. This emulates the \fBdocker\fR(1) command-line option \fB-l\fR.
.IP \(bu 4
\[lB]\fB-E\fR|\fB--environment\fR \fIkey\fR\fB=\fR\fIvalue\fR\[rB]: Inject a Docker environment variable into the created containers. This emulates the \fBdocker\fR(1) command-line option \fB-e\fR.
.IP \(bu 4
\[lB]\fB-B\fR|\fB--bind\fR \fIlocal-dir\fR\fB:\fR\fIremote-dir\fR\[lB]\fB:\fR\fIoptions\fR\[rB]\[rB]: Inject a Docker bind-mount into the created containers. This emulates the \fBdocker\fR(1) command-line option \fB-v\fR.
.IP \(bu 4
\[lB]\fB-a\fR|\fB--accept\fR \fIlocal-address\fR:\fIlocal-port\fR|\fIunix-socket-path\fR\[rB]: Accept new client connections on either the TCP socket \fIlocal-address\fR:\fIlocal-port\fR or the Unix domain socket \fIunix-socket-path\fR. The default is \fB127.0.0.1:12375\fR.
.IP \(bu 4
\[lB]\fB-c\fR|\fB--connect\fR \fIremote-address\fR:\fIremote-port\fR|\fIunix-socket-path\fR\[rB]: Connect to the Docker daemon, either via the TCP socket \fIremote-address\fR:\fIremote-port\fR or the Unix domain socket \fIunix-socket-path\fR. The default is \fB127.0.0.1:2375\fR.
.RE 0

.SH "EXAMPLES"
.P
The following inject SSL/TLS information of the Docker host into all created containers:
.P
.RS 2
.nf
$ docker-injector \[rs]
  -p docker-injector.pid -d \[rs]
  -l docker-injector.log -v 3 \[rs]
  -e SSL_CERT_DIR=/etc/ssl/certs \[rs]
  -e SSL_CERT_FILE=/etc/ssl/certs.pem \[rs]
  -e SSL_CERT_JKS=/etc/ssl/certs.jks \[rs]
  -e JAVA_TOOL_OPTIONS=-Djavax.net.ssl.trustStore=/etc/ssl/certs.jks \[rs]
  -e CURL_CA_PATH=/etc/ssl/certs \[rs]
  -e CURL_CA_BUNDLE=/etc/ssl/certs.pem \[rs]
  -m /etc/ssl:/etc/ssl:ro \[rs]
  -a 127.0.0.1:12375 -c 127.0.0.1:2375

$ export DOCKER_HOST=tcp://127.0.0.1:12375

$ docker version
.fi
.RE
.SH "HISTORY"
.P
The \fBdocker-injector\fR(1) utility was developed in March 2020 to automatically and transparently inject SSL/TLS information into every created Docker container in case one cannot directly control the container creation -- as it is the case, for instance, when \fBdrone-server\fR(8) runs its Docker containers via \fBdrone-runner-docker\fR(8).
.SH "AUTHOR"
.P
Dr. Ralf S. Engelschall \fI\(larse@engelschall.com\(ra\fR
